# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediaasset_cdn_url_mediaasset_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='how the page is referred to internally', max_length=160)),
                ('route', models.CharField(help_text="site-relative path, e.g. '/career' or '/subsidy'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='what this page is for; shown to maintainers')),
                ('group', models.CharField(blank=True, help_text="grouping for the Pages list, e.g. 'Solutions', 'Careers'", max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('is_protected', models.BooleanField(default=True, help_text='content/layout is developer-owned; only registered slots and SEO are editable')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sitepages_page',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageImageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='stable machine name the page component reads', max_length=60)),
                ('label', models.CharField(help_text='editable display name', max_length=120)),
                ('guidance', models.CharField(blank=True, help_text="e.g. 'landscape, at least 1600×900'", max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text="overrides the asset's own alt text for this placement", max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text="leave empty to keep the page's built-in image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_slots', to='media.mediaasset')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_slots', to='sitepages.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sitepages_page_image_slot',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='70–160 characters reads best in results')),
                ('canonical_url', models.URLField(blank=True, help_text='only when this URL duplicates another', max_length=1000)),
                ('schema_type', models.CharField(choices=[('none', 'No structured data'), ('WebPage', 'Web page'), ('Article', 'Article'), ('FAQPage', 'FAQ page'), ('JobPosting', 'Job posting'), ('Organization', 'Organization'), ('BreadcrumbList', 'Breadcrumb list')], default='none', max_length=32)),
                ('schema_extra', models.JSONField(blank=True, default=dict, help_text='only the structured fields the generator cannot infer from the record')),
                ('noindex', models.BooleanField(default=False, help_text='ask search engines not to index this URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='sitepages.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sitepages_page_seo',
            },
        ),
        migrations.CreateModel(
            name='PageTextSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='stable machine name the page component reads', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('short_text', 'Short text'), ('long_text', 'Long text'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone')], default='short_text', max_length=16)),
                ('guidance', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='cap enforced in the editor; null = uncapped', null=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_slots', to='sitepages.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sitepages_page_text_slot',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status'], name='sitepages_p_status_7a546a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['group'], name='sitepages_p_group_2a18b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageimageslot',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='uniq_image_slot_per_page'),
        ),
        migrations.AddConstraint(
            model_name='pagetextslot',
            constraint=models.UniqueConstraint(fields=('page', 'key'), name='uniq_text_slot_per_page'),
        ),
    ]
