# Generated by Django 5.2.1 on 2026-07-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'catalog_author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('color', models.CharField(default='#123532', max_length=32)),
            ],
            options={
                'db_table': 'catalog_badge',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_uid', models.SlugField(help_text="route slug, e.g. 'articles'", max_length=80, unique=True)),
                ('singular_name', models.CharField(max_length=80)),
                ('plural_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_collection',
                'ordering': ['plural_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'catalog_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_template',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAttributeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='stable machine name (contract)', max_length=60)),
                ('label', models.CharField(help_text='editable display name', max_length=120)),
                ('type', models.CharField(choices=[('text', 'Text'), ('richtext_blocks', 'Rich text (blocks)'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('enum', 'Enum'), ('url', 'URL')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict, help_text='{choices:[...]} for enum, {default,min,max} for number')),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_slots', to='catalog.template')),
            ],
            options={
                'db_table': 'catalog_template_attribute_slot',
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TemplateImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='stable machine name, e.g. coverImg / bodyImages', max_length=60)),
                ('label', models.CharField(help_text='editable display name', max_length=120)),
                ('repeatable', models.BooleanField(default=False)),
                ('max_items', models.PositiveIntegerField(blank=True, help_text='cap for repeatable; null = unbounded', null=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_groups', to='catalog.template')),
            ],
            options={
                'db_table': 'catalog_template_image_group',
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
