# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediaasset_cdn_url_mediaasset_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ categories',
                'db_table': 'faqs_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='70–160 characters reads best in results')),
                ('canonical_url', models.URLField(blank=True, help_text='only when this URL duplicates another', max_length=1000)),
                ('schema_type', models.CharField(choices=[('none', 'No structured data'), ('WebPage', 'Web page'), ('Article', 'Article'), ('FAQPage', 'FAQ page'), ('JobPosting', 'Job posting'), ('Organization', 'Organization'), ('BreadcrumbList', 'Breadcrumb list')], default='none', max_length=32)),
                ('schema_extra', models.JSONField(blank=True, default=dict, help_text='only the structured fields the generator cannot infer from the record')),
                ('noindex', models.BooleanField(default=False, help_text='ask search engines not to index this URL')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(help_text='light HTML is allowed — the site renders the same markup the schema carries')),
                ('section', models.CharField(blank=True, help_text='block within the page when it carries more than one FAQ list', max_length=80)),
                ('display_order', models.IntegerField(default=0, help_text='order within the page/section')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('og_image', models.ForeignKey(blank=True, help_text='social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'db_table': 'faqs_faq',
                'ordering': ['page', 'section', 'display_order', 'id'],
            },
        ),
    ]
