# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faqs', '0001_initial'),
        ('sitepages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.ForeignKey(help_text='the website page this FAQ appears on', on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='sitepages.page'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='faqs.faqcategory'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['page', 'section', 'display_order'], name='faqs_faq_page_id_0b4faa_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['status'], name='faqs_faq_status_480534_idx'),
        ),
    ]
