# Generated by Django 5.2.1 on 2026-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='light HTML is allowed — the site renders the same markup the schema carries'),
        ),
    ]
