from django.core.management.base import BaseCommand
from goldenray.models import SolarInverter


class Command(BaseCommand):
    help = 'Populate database with solar inverters for the comparison page'

    def handle(self, *args, **options):
        inverters_data = [
            {
                # 1. Enphase IQ8P Microinverter
                'brand': 'Enphase',
                'name': 'Enphase IQ8P Microinverter',
                'inverter_type': 'microinverter',
                'rating_tier': 'premium',
                'image_url': '',
                'description': 'IP68 grid-forming microinverter. Each panel gets its own 480VA inverter — no single point of failure, no shading losses, and per-panel monitoring via the Enphase App. 15-year warranty extendable to 25. 100% Kerala capability. Premium cost, but unmatched reliability and monitoring for complex Kerala rooftops.',
                'rated_output_power': 480,
                'maximum_dc_input': 540,
                'mppt_trackers': 1,
                'maximum_dc_voltage': 60,
                'maximum_input_current': '14 A',
                'weight': 1.08,
                'display': 'Enphase App',
                'suitable_system_size': 'Per-panel — any size',
                'maximum_efficiency': 97.5,
                'european_efficiency': 97.3,
                'mppt_efficiency': 99.5,
                'dc_oversizing': 150,
                'ac_overloading': 110,
                'pid_protection': True,
                'iv_curve_scanning': 'Advanced diagnostics',
                'ip_rating': 'IP68',
                'corrosion_protection': 'C5 Rated (Coastal protection)',
                'operating_temperature': '-40°C to 65°C',
                'cooling': 'Natural convection',
                'noise_level': 'Silent',
                'dc_surge_protection': 'Built-in',
                'ac_surge_protection': 'Built-in',
                'arc_fault_detection': 'Built-in',
                'grid_protection': True,
                'monitoring_app': 'Enphase App',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Advanced IV Scan',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 15,
                'extendable_warranty_years': 25,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS', 'UL 1741'],
                'brand_trust': 'Available',
                'year_founded': 2006,
                'countries_served': '150+ Countries',
                'global_installations': '4 million+ systems',
                'price_range': '₹₹₹₹',
                'kerala_climate_score': 94,
                'efficiency_rating': 97,
                'reliability_rating': 98,
                'warranty_rating': 95,
                'kerala_climate_rating': 93,
                'overall_rating': 'excellent',
            },
            {
                # 2. SolarEdge SE5000H HD-Wave (Optimized String)
                'brand': 'SolarEdge',
                'name': 'SolarEdge SE5000H HD-Wave',
                'inverter_type': 'optimized-string',
                'rating_tier': 'premium',
                'image_url': '',
                'description': 'The world\'s most efficient string inverter at 99%. Uses HD-Wave technology for dramatically smaller size and weight. Requires SolarEdge Power Optimizers on each panel for module-level optimization — giving you panel-level monitoring like a microinverter at a lower cost. 12-year warranty extendable to 25. Built-in arc fault and rapid shutdown.',
                'rated_output_power': 5000,
                'maximum_dc_input': 7500,
                'mppt_trackers': 2,
                'maximum_dc_voltage': 500,
                'maximum_input_current': '14 A per MPPT',
                'weight': 10.8,
                'display': 'LED + Mobile App',
                'suitable_system_size': 'Ideal for 5 kW homes',
                'maximum_efficiency': 98.4,
                'european_efficiency': 97.3,
                'mppt_efficiency': 99.9,
                'dc_oversizing': 140,
                'ac_overloading': 110,
                'pid_protection': False,
                'iv_curve_scanning': 'Not available',
                'ip_rating': 'IP65',
                'corrosion_protection': 'Standard coating',
                'operating_temperature': '-25°C to 60°C',
                'cooling': 'Natural convection',
                'noise_level': '<25 dB',
                'dc_surge_protection': 'Optional',
                'ac_surge_protection': 'Optional',
                'arc_fault_detection': 'Optional',
                'grid_protection': True,
                'monitoring_app': 'ShinePhone / SEMS',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Basic alerts',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 12,
                'extendable_warranty_years': 25,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS'],
                'brand_trust': 'Available',
                'year_founded': 2006,
                'countries_served': '100+ Countries',
                'global_installations': '269+ GW',
                'price_range': '₹₹₹',
                'kerala_climate_score': 90,
                'efficiency_rating': 94,
                'reliability_rating': 94,
                'warranty_rating': 93,
                'kerala_climate_rating': 90,
                'overall_rating': 'excellent',
            },
            {
                # 3. Fronius Primo GEN24 5.0 (Hybrid)
                'brand': 'Fronius',
                'name': 'Fronius Primo GEN24 5.0',
                'inverter_type': 'hybrid',
                'rating_tier': 'premium',
                'image_url': '',
                'description': 'Austrian-engineered hybrid with PV-Point backup power — keeps essential loads running during a brownout without a battery. Active cooling technology maintains 98.1% output at high temperatures. Dynamic Peak Manager handles shading & string-level fluctuations on partial-shading Kerala rooftops. Premium build quality with European manufacturing standards.',
                'rated_output_power': 5000,
                'maximum_dc_input': 7500,
                'mppt_trackers': 2,
                'maximum_dc_voltage': 600,
                'maximum_input_current': '12 A per MPPT',
                'weight': 14.9,
                'display': 'LED + Mobile App',
                'suitable_system_size': 'Ideal for 5-6 kW homes',
                'maximum_efficiency': 98.1,
                'european_efficiency': 97.6,
                'mppt_efficiency': 99.9,
                'dc_oversizing': 150,
                'ac_overloading': 110,
                'pid_protection': True,
                'iv_curve_scanning': 'Advanced diagnostics',
                'ip_rating': 'IP66',
                'corrosion_protection': 'C5 Rated (Coastal protection)',
                'operating_temperature': '-25°C to 60°C',
                'cooling': 'Active cooling',
                'noise_level': '<35 dB',
                'dc_surge_protection': 'Built-in',
                'ac_surge_protection': 'Built-in',
                'arc_fault_detection': 'Built-in',
                'grid_protection': True,
                'monitoring_app': 'Fronius Solar.web',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Advanced IV Scan',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 10,
                'extendable_warranty_years': 20,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS', 'VDE-AR-N 4105'],
                'brand_trust': 'Available',
                'year_founded': 1945,
                'countries_served': '80+ Countries',
                'global_installations': '20 GW+',
                'price_range': '₹₹₹₹',
                'kerala_climate_score': 91,
                'efficiency_rating': 95,
                'reliability_rating': 96,
                'warranty_rating': 82,
                'kerala_climate_rating': 91,
                'overall_rating': 'excellent',
            },
            {
                # 4. Sungrow SG5.0RS (String Inverter)
                'brand': 'Sungrow',
                'name': 'Sungrow SG5.0RS',
                'inverter_type': 'string',
                'rating_tier': 'mid-range',
                'image_url': '',
                'description': 'World\'s most bankable inverter brand (No.1 globally). The SG5.0RS is the sweet spot — 97.9% efficiency, dual MPPT, built-in AFCI / arc-fault protection, and C5 corrosion rating (critical for coastal Kerala). While MPPT range (40-560V) with PID Zero function. Smart-V Local Scanning for remote diagnostics. 10-year warranty extendable to 25. The reliability benchmark at mid-range pricing.',
                'rated_output_power': 5000,
                'maximum_dc_input': 7500,
                'mppt_trackers': 2,
                'maximum_dc_voltage': 600,
                'maximum_input_current': '16 A per MPPT',
                'weight': 10.0,
                'display': 'LED + Mobile App',
                'suitable_system_size': 'Ideal for 5-6 kW homes',
                'maximum_efficiency': 97.9,
                'european_efficiency': 97.3,
                'mppt_efficiency': 99.5,
                'dc_oversizing': 150,
                'ac_overloading': 110,
                'pid_protection': True,
                'iv_curve_scanning': 'Advanced diagnostics',
                'ip_rating': 'IP65',
                'corrosion_protection': 'C5 Rated (Coastal protection)',
                'operating_temperature': '-25°C to 60°C',
                'cooling': 'Natural convection',
                'noise_level': '<30 dB',
                'dc_surge_protection': 'Built-in',
                'ac_surge_protection': 'Built-in',
                'arc_fault_detection': 'Built-in',
                'grid_protection': True,
                'monitoring_app': 'iSolarCloud',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Advanced IV Scan',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 10,
                'extendable_warranty_years': 25,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS', 'IS 16221'],
                'brand_trust': 'Available',
                'year_founded': 1997,
                'countries_served': '150+ Countries',
                'global_installations': '269+ GW',
                'price_range': '₹₹₹',
                'kerala_climate_score': 92,
                'efficiency_rating': 96,
                'reliability_rating': 94,
                'warranty_rating': 96,
                'kerala_climate_rating': 92,
                'overall_rating': 'excellent',
            },
            {
                # 5. Growatt MIN 5000TL-X (Value String)
                'brand': 'Growatt',
                'name': 'Growatt MIN 5000TL-X',
                'inverter_type': 'string',
                'rating_tier': 'value',
                'image_url': '',
                'description': 'Budget-friendly string inverter with strong efficiency (98.4%) and lightweight design (10.8 kg). Standard corrosion coating means it suits inland or roof-covered installations — not ideal for direct coastal exposure in Kerala. Optional DC/AC surge protection. Solid choice for cost-sensitive Tier-2 / Tier-3 homes; pair with SPD add-ons for full coastal safety.',
                'rated_output_power': 5000,
                'maximum_dc_input': 7500,
                'mppt_trackers': 2,
                'maximum_dc_voltage': 500,
                'maximum_input_current': '14 A per MPPT',
                'weight': 10.8,
                'display': 'LED + Mobile App',
                'suitable_system_size': 'Ideal for 5 kW homes',
                'maximum_efficiency': 98.4,
                'european_efficiency': 97.3,
                'mppt_efficiency': 99.9,
                'dc_oversizing': 140,
                'ac_overloading': 110,
                'pid_protection': False,
                'iv_curve_scanning': 'Not available',
                'ip_rating': 'IP65',
                'corrosion_protection': 'Standard coating',
                'operating_temperature': '-25°C to 60°C',
                'cooling': 'Natural convection',
                'noise_level': '<25 dB',
                'dc_surge_protection': 'Optional',
                'ac_surge_protection': 'Optional',
                'arc_fault_detection': 'Optional',
                'grid_protection': True,
                'monitoring_app': 'ShinePhone / SEMS',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Basic alerts',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 10,
                'extendable_warranty_years': 25,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS'],
                'brand_trust': 'Available',
                'year_founded': 2010,
                'countries_served': '100+ Countries',
                'global_installations': '269+ GW',
                'price_range': '₹₹',
                'kerala_climate_score': 80,
                'efficiency_rating': 94,
                'reliability_rating': 84,
                'warranty_rating': 90,
                'kerala_climate_rating': 80,
                'overall_rating': 'very-good',
            },
            {
                # 6. GoodWe GW5000-MS (Mid-range String)
                'brand': 'GoodWe',
                'name': 'GoodWe GW5000-MS',
                'inverter_type': 'string',
                'rating_tier': 'mid-range',
                'image_url': '',
                'description': 'Reliable Chinese-engineered string inverter with strong Indian service presence and IP65 rating. Dual MPPT with built-in DC surge protection makes it a balanced pick for typical Kerala rooftops away from the immediate coast. SEMS portal app for monitoring, OTA firmware updates, and a 10-year standard warranty extendable to 25.',
                'rated_output_power': 5000,
                'maximum_dc_input': 6500,
                'mppt_trackers': 2,
                'maximum_dc_voltage': 550,
                'maximum_input_current': '12.5 A per MPPT',
                'weight': 10.5,
                'display': 'LED + Mobile App',
                'suitable_system_size': 'Ideal for 5 kW homes',
                'maximum_efficiency': 97.8,
                'european_efficiency': 97.2,
                'mppt_efficiency': 99.5,
                'dc_oversizing': 130,
                'ac_overloading': 110,
                'pid_protection': True,
                'iv_curve_scanning': 'Basic',
                'ip_rating': 'IP65',
                'corrosion_protection': 'Standard coating',
                'operating_temperature': '-25°C to 60°C',
                'cooling': 'Natural convection',
                'noise_level': '<30 dB',
                'dc_surge_protection': 'Built-in',
                'ac_surge_protection': 'Optional',
                'arc_fault_detection': 'Optional',
                'grid_protection': True,
                'monitoring_app': 'SEMS Portal',
                'real_time_monitoring': True,
                'remote_diagnostics': 'Basic alerts',
                'firmware_updates': 'OTA Updates',
                'connectivity': 'WiFi / Ethernet',
                'warranty_years': 10,
                'extendable_warranty_years': 25,
                'certifications': ['IEC 62109', 'IEC 61727', 'CE', 'BIS'],
                'brand_trust': 'Available',
                'year_founded': 2010,
                'countries_served': '100+ Countries',
                'global_installations': '50 GW+',
                'price_range': '₹₹',
                'kerala_climate_score': 84,
                'efficiency_rating': 93,
                'reliability_rating': 88,
                'warranty_rating': 92,
                'kerala_climate_rating': 84,
                'overall_rating': 'very-good',
            },
        ]

        created_count = 0
        updated_count = 0

        for inverter_data in inverters_data:
            inverter, created = SolarInverter.objects.update_or_create(
                brand=inverter_data['brand'],
                name=inverter_data['name'],
                defaults=inverter_data,
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f"✓ Created: {inverter.brand} {inverter.name}"))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f"↻ Updated: {inverter.brand} {inverter.name}"))

        self.stdout.write(self.style.SUCCESS(f"\n✅ Processed {len(inverters_data)} solar inverters"))
        self.stdout.write(self.style.SUCCESS(f"   Created: {created_count}"))
        self.stdout.write(self.style.SUCCESS(f"   Updated: {updated_count}"))
