# Generated by Django 5.2.1 on 2025-06-01 16:00

from django.db import migrations


def insert_device_types(apps, schema_editor):
    DeviceType = apps.get_model("goldenray", "DeviceType")
    device_types = [
        {"name": "AC", "show_in_ui": True},
        {"name": "Washing Machine", "show_in_ui": True},
        {"name": "TV", "show_in_ui": True},
        {"name": "Printer", "show_in_ui": True},
        {"name": "Air Fryer", "show_in_ui": True},
        {"name": "Cooker", "show_in_ui": True},
        {"name": "Refrigerator", "show_in_ui": True},
        {"name": "Microwave", "show_in_ui": True},
        {"name": "Toaster", "show_in_ui": True},
        {"name": "Blender", "show_in_ui": True},
        {"name": "Dishwasher", "show_in_ui": True},
        {"name": "Vacuum Cleaner", "show_in_ui": True},
        {"name": "Electric Kettle", "show_in_ui": True},
        {"name": "Fan", "show_in_ui": True},
        {"name": "Heater", "show_in_ui": True},
        {"name": "Iron", "show_in_ui": True},
    ]
    for device_type in device_types:
        DeviceType.objects.create(**device_type)


def remove_device_types(apps, schema_editor):
    DeviceType = apps.get_model("goldenray", "DeviceType")
    DeviceType.objects.filter(
        name__in=[
            "AC",
            "Washing Machine",
            "TV",
            "Printer",
            "Air Fryer",
            "Cooker",
            "Refrigerator",
            "Microwave",
            "Toaster",
            "Blender",
            "Dishwasher",
            "Vacuum Cleaner",
            "Electric Kettle",
            "Fan",
            "Heater",
            "Iron",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("goldenray", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insert_device_types, remove_device_types),
    ]
