# Generated by Django 5.2.1 on 2025-06-01 16:11

from django.db import migrations


def insert_wattages(apps, schema_editor):
    Wattage = apps.get_model("goldenray", "Wattage")
    wattage_values = [
        {"value": 10, "show_in_ui": True},  # LED Bulb
        {"value": 24, "show_in_ui": True},  # Small Fan
        {"value": 40, "show_in_ui": True},  # Ceiling Fan
        {"value": 50, "show_in_ui": True},  # TV (Small LED)
        {"value": 60, "show_in_ui": True},  # Electric Kettle (Small)
        {"value": 75, "show_in_ui": True},  # Blender
        {"value": 100, "show_in_ui": True},  # Toaster
        {"value": 120, "show_in_ui": True},  # Vacuum Cleaner (Small)
        {"value": 150, "show_in_ui": True},  # Refrigerator (Small)
        {"value": 200, "show_in_ui": True},  # Microwave (Small)
        {"value": 300, "show_in_ui": True},  # Air Fryer
        {"value": 350, "show_in_ui": True},  # Washing Machine (Low-end)
        {"value": 400, "show_in_ui": True},  # Printer (Laser)
        {"value": 500, "show_in_ui": True},  # Dishwasher (Compact)
        {"value": 600, "show_in_ui": True},  # Cooker (Electric)
        {"value": 700, "show_in_ui": True},  # Heater (Small)
        {"value": 800, "show_in_ui": True},  # Iron
        {"value": 900, "show_in_ui": True},  # Coffee Maker
        {"value": 1000, "show_in_ui": True},  # AC (Small Window Unit)
        {"value": 1200, "show_in_ui": True},  # Microwave (Large)
        {"value": 1500, "show_in_ui": True},  # Electric Kettle (Large)
        {"value": 1800, "show_in_ui": True},  # Clothes Dryer (Small)
        {"value": 2000, "show_in_ui": True},  # Heater (Large)
        {"value": 2400, "show_in_ui": True},  # Dishwasher (Large)
        {"value": 3000, "show_in_ui": True},  # AC (Large Split Unit)
    ]
    for wattage in wattage_values:
        Wattage.objects.create(**wattage)


def remove_wattages(apps, schema_editor):
    Wattage = apps.get_model("goldenray", "Wattage")
    Wattage.objects.filter(value__in=[10, 24, 40, 50, 60, 75, 100, 120, 150, 200, 300, 350, 400, 500, 600, 700, 800, 900, 1000, 1200, 1500, 1800, 2000, 2400, 3000]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("goldenray", "0003_wattage"),
    ]

    operations = [
        migrations.RunPython(insert_wattages, remove_wattages),
    ]
