# Generated by Django 5.2.1 on 2025-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0004_insert_wattages'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSEBTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.IntegerField()),
                ('max_units', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kseb_tariffs',
            },
        ),
    ]
