# Generated by Django 5.2.1 on 2025-06-01 17:00

from django.db import migrations


def insert_kseb_tariffs(apps, schema_editor):
    KSEBTariff = apps.get_model("goldenray", "KSEBTariff")
    tariffs = [
        {"min_units": 0, "max_units": 300, "rate": 6.40},
        {"min_units": 301, "max_units": 350, "rate": 7.25},
        {"min_units": 351, "max_units": 400, "rate": 7.60},
        {"min_units": 401, "max_units": 500, "rate": 7.90},
        {"min_units": 501, "max_units": None, "rate": 8.80},
    ]
    KSEBTariff.objects.bulk_create([KSEBTariff(**tariff) for tariff in tariffs])


def remove_kseb_tariffs(apps, schema_editor):
    KSEBTariff = apps.get_model("goldenray", "KSEBTariff")
    KSEBTariff.objects.filter(min_units__in=[0, 301, 351, 401, 501]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0005_ksebtariff'),
    ]

    operations = [
        migrations.RunPython(insert_kseb_tariffs, remove_kseb_tariffs),
    ]