# Generated by Django 5.2.1 on 2025-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0006_insert_kseb_tariffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('battery_capacity', models.FloatField()),
                ('claimed_range', models.IntegerField()),
                ('adjusted_real_world_range', models.IntegerField()),
                ('ex_showroom_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ev_cars',
            },
        ),
        migrations.CreateModel(
            name='EVScooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('battery_capacity', models.FloatField()),
                ('claimed_range', models.IntegerField()),
                ('adjusted_real_world_range', models.IntegerField()),
                ('ex_showroom_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ev_scooters',
            },
        ),
    ]
