# Generated by Django 5.2.1 on 2025-06-01 17:30

from django.db import migrations


def insert_ev_cars_and_scooters(apps, schema_editor):
    EVCar = apps.get_model("goldenray", "EVCar")
    EVScooter = apps.get_model("goldenray", "EVScooter")

    # Insert EV Cars
    cars = [
        {"model": "Tata Nexon EV", "battery_capacity": 30.2, "claimed_range": 312, "adjusted_real_world_range": 212, "ex_showroom_price": 1249000},
        {"model": "Tata Tigor EV", "battery_capacity": 26.0, "claimed_range": 250, "adjusted_real_world_range": 150, "ex_showroom_price": 1199000},
        {"model": "MG ZS EV", "battery_capacity": 50.3, "claimed_range": 461, "adjusted_real_world_range": 361, "ex_showroom_price": 1648000},
        {"model": "Hyundai Kona Electric", "battery_capacity": 39.2, "claimed_range": 452, "adjusted_real_world_range": 352, "ex_showroom_price": 2384000},
        {"model": "Mahindra XUV400", "battery_capacity": 39.4, "claimed_range": 456, "adjusted_real_world_range": 356, "ex_showroom_price": 1599000},
        {"model": "Tata Tiago EV", "battery_capacity": 24.0, "claimed_range": 250, "adjusted_real_world_range": 150, "ex_showroom_price": 799000},
        {"model": "MG Comet EV", "battery_capacity": 17.3, "claimed_range": 230, "adjusted_real_world_range": 130, "ex_showroom_price": 617000},
        {"model": "Tata Punch EV", "battery_capacity": 25.0, "claimed_range": 315, "adjusted_real_world_range": 215, "ex_showroom_price": 999000},
        {"model": "Hyundai Creta Electric", "battery_capacity": 51.4, "claimed_range": 473, "adjusted_real_world_range": 373, "ex_showroom_price": 1799000},
        {"model": "Mahindra BE 6", "battery_capacity": 59.0, "claimed_range": 556, "adjusted_real_world_range": 456, "ex_showroom_price": 1890000},
        {"model": "Mahindra XEV 9e", "battery_capacity": 59.0, "claimed_range": 542, "adjusted_real_world_range": 442, "ex_showroom_price": 2190000},
        {"model": "MG Windsor EV", "battery_capacity": 38.0, "claimed_range": 332, "adjusted_real_world_range": 232, "ex_showroom_price": 1400000},
        {"model": "Tata Curvv EV", "battery_capacity": 45.0, "claimed_range": 430, "adjusted_real_world_range": 330, "ex_showroom_price": 1749000},
        {"model": "Maruti Suzuki e Vitara", "battery_capacity": 49.0, "claimed_range": 400, "adjusted_real_world_range": 300, "ex_showroom_price": 1200000},
    ]
    EVCar.objects.bulk_create([EVCar(**car) for car in cars])

    # Insert EV Scooters
    scooters = [
        {"model": "Ola S1 Pro", "battery_capacity": 4.0, "claimed_range": 181, "adjusted_real_world_range": 81, "ex_showroom_price": 130000},
        {"model": "Ather 450X", "battery_capacity": 3.7, "claimed_range": 100, "adjusted_real_world_range": 0, "ex_showroom_price": 135000},
        {"model": "TVS iQube", "battery_capacity": 3.0, "claimed_range": 145, "adjusted_real_world_range": 45, "ex_showroom_price": 94434},
        {"model": "Bajaj Chetak", "battery_capacity": 3.0, "claimed_range": 153, "adjusted_real_world_range": 53, "ex_showroom_price": 99998},
        {"model": "Hero Vida V1", "battery_capacity": 3.9, "claimed_range": 165, "adjusted_real_world_range": 65, "ex_showroom_price": 110000},
        {"model": "Simple One", "battery_capacity": 4.8, "claimed_range": 236, "adjusted_real_world_range": 136, "ex_showroom_price": 110000},
        {"model": "Honda Activa e", "battery_capacity": 3.0, "claimed_range": 102, "adjusted_real_world_range": 2, "ex_showroom_price": 117000},
        {"model": "Suzuki e-Access", "battery_capacity": 3.0, "claimed_range": 100, "adjusted_real_world_range": 0, "ex_showroom_price": 100000},
        {"model": "Yulu Wynn", "battery_capacity": 0.9, "claimed_range": 68, "adjusted_real_world_range": 0, "ex_showroom_price": 55555},
        {"model": "Ampere Magnus Neo", "battery_capacity": 2.0, "claimed_range": 121, "adjusted_real_world_range": 21, "ex_showroom_price": 77000},
        {"model": "BGauss C12i", "battery_capacity": 2.5, "claimed_range": 123, "adjusted_real_world_range": 23, "ex_showroom_price": 99990},
        {"model": "Okinawa Okhi-90", "battery_capacity": 3.6, "claimed_range": 160, "adjusted_real_world_range": 60, "ex_showroom_price": 121000},
        {"model": "Revolt RV400", "battery_capacity": 3.2, "claimed_range": 150, "adjusted_real_world_range": 50, "ex_showroom_price": 124000},
        {"model": "Ultraviolette Tesseract", "battery_capacity": 3.5, "claimed_range": 167, "adjusted_real_world_range": 67, "ex_showroom_price": 120000},
        {"model": "Ather Rizta", "battery_capacity": 2.9, "claimed_range": 123, "adjusted_real_world_range": 23, "ex_showroom_price": 132000},
    ]
    EVScooter.objects.bulk_create([EVScooter(**scooter) for scooter in scooters])


def remove_ev_cars_and_scooters(apps, schema_editor):
    EVCar = apps.get_model("goldenray", "EVCar")
    EVScooter = apps.get_model("goldenray", "EVScooter")
    EVCar.objects.filter(
        model__in=[
            "Tata Nexon EV",
            "Tata Tigor EV",
            "MG ZS EV",
            "Hyundai Kona Electric",
            "Mahindra XUV400",
            "Tata Tiago EV",
            "MG Comet EV",
            "Tata Punch EV",
            "Hyundai Creta Electric",
            "Mahindra BE 6",
            "Mahindra XEV 9e",
            "MG Windsor EV",
            "Tata Curvv EV",
            "Maruti Suzuki e Vitara",
        ]
    ).delete()
    EVScooter.objects.filter(
        model__in=[
            "Ola S1 Pro",
            "Ather 450X",
            "TVS iQube",
            "Bajaj Chetak",
            "Hero Vida V1",
            "Simple One",
            "Honda Activa e",
            "Suzuki e-Access",
            "Yulu Wynn",
            "Ampere Magnus Neo",
            "BGauss C12i",
            "Okinawa Okhi-90",
            "Revolt RV400",
            "Ultraviolette Tesseract",
            "Ather Rizta",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("goldenray", "0007_evcar_evscooter"),
    ]

    operations = [
        migrations.RunPython(insert_ev_cars_and_scooters, remove_ev_cars_and_scooters),
    ]
