# Generated by Django 5.2.1 on 2025-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0008_insert_ev_cars_and_scooters'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_capacity', models.FloatField()),
                ('time_to_complete', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_subsidy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_required', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solar_installations',
            },
        ),
    ]
