# Generated by Django 5.2.1 on 2025-06-01

from django.db import migrations


def insert_solar_installations(apps, schema_editor):
    SolarInstallation = apps.get_model("goldenray", "SolarInstallation")
    installations = [
        {"power_capacity": 4.0, "time_to_complete": 4, "total_cost": 272000.00, "total_subsidy": 78000.00, "area_required": 320},
        {"power_capacity": 8.0, "time_to_complete": 6, "total_cost": 544000.00, "total_subsidy": 156000.00, "area_required": 640},
        {"power_capacity": 5.0, "time_to_complete": 5, "total_cost": 340000.00, "total_subsidy": 97500.00, "area_required": 400},
        {"power_capacity": 10.0, "time_to_complete": 7, "total_cost": 680000.00, "total_subsidy": 195000.00, "area_required": 800},
        {"power_capacity": 3.0, "time_to_complete": 3, "total_cost": 204000.00, "total_subsidy": 58500.00, "area_required": 240},
        {"power_capacity": 6.0, "time_to_complete": 5, "total_cost": 408000.00, "total_subsidy": 117000.00, "area_required": 480},
        {"power_capacity": 12.0, "time_to_complete": 8, "total_cost": 816000.00, "total_subsidy": 234000.00, "area_required": 960},
        {"power_capacity": 7.0, "time_to_complete": 6, "total_cost": 476000.00, "total_subsidy": 136500.00, "area_required": 560},
        {"power_capacity": 9.0, "time_to_complete": 7, "total_cost": 612000.00, "total_subsidy": 175500.00, "area_required": 720},
        {"power_capacity": 15.0, "time_to_complete": 10, "total_cost": 1020000.00, "total_subsidy": 292500.00, "area_required": 1200},
    ]
    SolarInstallation.objects.bulk_create([SolarInstallation(**installation) for installation in installations])


def remove_solar_installations(apps, schema_editor):
    SolarInstallation = apps.get_model("goldenray", "SolarInstallation")
    SolarInstallation.objects.filter(power_capacity__in=[4.0, 8.0, 5.0, 10.0, 3.0, 6.0, 12.0, 7.0, 9.0, 15.0]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("goldenray", "0009_solarinstallation"),
    ]

    operations = [
        migrations.RunPython(insert_solar_installations, remove_solar_installations),
    ]
