# Generated by Django 5.2.1 on 2025-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0010_insert_solar_installations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('office_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pincodes',
            },
        ),
    ]
