# Generated by Django 5.2.1 on 2025-06-02

import csv
import os
from django.db import migrations


def insert_kerala_pincodes(apps, schema_editor):
    Pincode = apps.get_model("goldenray", "Pincode")
    csv_file_path = os.path.join(os.path.dirname(__file__), 'data', 'pincodes.csv')  # Adjust path as needed
    with open(csv_file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['statename'].upper() == 'KERALA':
                Pincode.objects.create(
                    pincode=row['pincode'],
                    state=row['statename'],
                    district=row['district'],
                    office_name=row['officename'],
                    region=row['regionname'],
                    division=row['divisionname']
                )


def remove_kerala_pincodes(apps, schema_editor):
    Pincode = apps.get_model("goldenray", "Pincode")
    Pincode.objects.filter(state='KERALA').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0011_pincode'),
    ]

    operations = [
        migrations.RunPython(insert_kerala_pincodes, remove_kerala_pincodes),
    ]