# Generated by Django 5.2.1 on 2025-06-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0013_sentquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInstallationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_range', models.IntegerField()),
                ('power_capacity', models.FloatField()),
                ('time_to_complete', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_subsidy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_required', models.IntegerField()),
                ('loan_available', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solar_installation_new',
            },
        ),
    ]
