# Generated by Django 5.2.1 on 2025-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0015_insert_solar_installation_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
