# Generated by Django 5.2.1 on 2025-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0017_insert_devicetype_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarinstallationnew',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationnew',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationnew',
            name='per_kw_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationnew',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
