from django.db import migrations
from django.utils import timezone


def insert_solar_installation_new_rows(apps, schema_editor):
    SolarInstallationNew = apps.get_model("goldenray", "SolarInstallationNew")
    now = timezone.now()
    data = [
        {
            "bill_range": 24000,
            "power_capacity": 12.0,
            "time_to_complete": "3-18",
            "total_cost": 720000.00,
            "total_subsidy": 78000.00,
            "area_required": 960,
            "loan_available": "2,00,000-6,00,000",
            "per_kw_rate": 60000.00,
            "final_cost": 642000.00,
            "interest_rate": 9.15,
            "type": "Residential",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 30000,
            "power_capacity": 15.0,
            "time_to_complete": "3-18",
            "total_cost": 900000.00,
            "total_subsidy": 78000.00,
            "area_required": 1200,
            "loan_available": "2,00,000-6,00,000",
            "per_kw_rate": 60000.00,
            "final_cost": 822000.00,
            "interest_rate": 9.15,
            "type": "Residential",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 40000,
            "power_capacity": 20.0,
            "time_to_complete": "3-18",
            "total_cost": 1200000.00,
            "total_subsidy": 78000.00,
            "area_required": 1600,
            "loan_available": "2,00,000-6,00,000",
            "per_kw_rate": 60000.00,
            "final_cost": 1122000.00,
            "interest_rate": 9.15,
            "type": "Residential",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 6000,
            "power_capacity": 3.0,
            "time_to_complete": "3-7",
            "total_cost": 230000.00,
            "total_subsidy": 0.00,
            "area_required": 240,
            "loan_available": "N/A",
            "per_kw_rate": 76667.00,
            "final_cost": 230000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 8000,
            "power_capacity": 4.0,
            "time_to_complete": "3-7",
            "total_cost": 277000.00,
            "total_subsidy": 0.00,
            "area_required": 320,
            "loan_available": "N/A",
            "per_kw_rate": 69250.00,
            "final_cost": 277000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 10000,
            "power_capacity": 5.0,
            "time_to_complete": "3-7",
            "total_cost": 330000.00,
            "total_subsidy": 0.00,
            "area_required": 400,
            "loan_available": "N/A",
            "per_kw_rate": 66000.00,
            "final_cost": 330000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 15500,
            "power_capacity": 8.0,
            "time_to_complete": "3-10",
            "total_cost": 525000.00,
            "total_subsidy": 0.00,
            "area_required": 640,
            "loan_available": "N/A",
            "per_kw_rate": 65625.00,
            "final_cost": 525000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 20000,
            "power_capacity": 10.0,
            "time_to_complete": "3-13",
            "total_cost": 600000.00,
            "total_subsidy": 0.00,
            "area_required": 800,
            "loan_available": "N/A",
            "per_kw_rate": 60000.00,
            "final_cost": 600000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 24000,
            "power_capacity": 12.0,
            "time_to_complete": "3-18",
            "total_cost": 720000.00,
            "total_subsidy": 0.00,
            "area_required": 960,
            "loan_available": "N/A",
            "per_kw_rate": 60000.00,
            "final_cost": 720000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 30000,
            "power_capacity": 15.0,
            "time_to_complete": "3-18",
            "total_cost": 900000.00,
            "total_subsidy": 0.00,
            "area_required": 1200,
            "loan_available": "N/A",
            "per_kw_rate": 60000.00,
            "final_cost": 900000.00,
            "interest_rate": 0.0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        {
            "bill_range": 40000,
            "power_capacity": 20.0,
            "time_to_complete": "3-18",
            "total_cost": 1200000.00,
            "total_subsidy": 0.00,
            "area_required": 1600,
            "loan_available": "N/A",
            "per_kw_rate": 60000.00,
            "final_cost": 1200000.00,
            "interest_rate": 0,
            "type": "Commercial",
            "created_at": now,
            "updated_at": now,
        },
        
    ]
    SolarInstallationNew.objects.bulk_create([
        SolarInstallationNew(**entry) for entry in data
    ])

def reverse_func(apps, schema_editor):
    SolarInstallationNew = apps.get_model("goldenray", "SolarInstallationNew")
    SolarInstallationNew.objects.filter(bill_range__in=[25000, 30000]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ("goldenray", "0019_update_and_insert_solar_installation_new"),
    ]

    operations = [
        migrations.RunPython(insert_solar_installation_new_rows, reverse_func),
    ] 