# Generated by Django 5.2.1 on 2025-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0020_insert_solar_installation_new_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcar',
            name='energy_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
