# Generated by Django 5.2.1 on 2025-06-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0022_update_evcar_energy_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='evscooter',
            name='energy_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
