# Generated by Django 5.2.1 on 2025-06-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0024_update_evscooter_energy_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('backup_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inverter_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batteries',
            },
        ),
    ]
