# Generated by Django 5.2.1 on 2025-06-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0026_insert_battery_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='watts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
