# Generated by Django 5.2.1 on 2025-07-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0034_set_inverter_price_solarinstallationnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCollectionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_collection_home',
            },
        ),
    ]
