# Generated by Django 5.2.1 on 2025-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0035_leadcollectionhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.JSONField()),
                ('imageUrl', models.CharField(max_length=255)),
                ('ogtype', models.CharField(max_length=50)),
            ],
        ),
    ]
