# Generated by Django 5.0.2 on 2025-10-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0040_insert_room_size_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcar',
            name='k_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evscooter',
            name='k_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
