# Generated by Django 5.0.2 on 2025-10-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0041_evcar_k_value_evscooter_k_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='k_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
