# Generated by Django 6.0.1 on 2026-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0045_update_interest_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('pincode', models.CharField(db_index=True, max_length=6)),
                ('address', models.TextField()),
                ('system_size', models.FloatField(help_text='System size in kW')),
                ('installation_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_installations',
                'indexes': [models.Index(fields=['pincode'], name='customer_in_pincode_a2fef4_idx'), models.Index(fields=['installation_date'], name='customer_in_install_99a4c2_idx'), models.Index(fields=['status'], name='customer_in_status_d92985_idx')],
            },
        ),
    ]
