# Generated by Django 6.0.1 on 2026-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0046_customerinstallation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('wattage', models.IntegerField()),
                ('panel_type', models.CharField(choices=[('monocrystalline', 'Monocrystalline'), ('polycrystalline', 'Polycrystalline'), ('bifacial', 'Bifacial')], max_length=50)),
                ('technology', models.CharField(choices=[('n-type-topcon', 'N-Type TOPCon'), ('p-type-perc', 'P-Type PERC'), ('hjt', 'HJT'), ('ibc', 'IBC')], max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temperature_coefficient', models.DecimalField(decimal_places=2, max_digits=4)),
                ('noct', models.IntegerField()),
                ('real_output_at_60c', models.IntegerField()),
                ('ip_rating', models.CharField(default='IP67', max_length=10)),
                ('wind_load', models.IntegerField()),
                ('moisture_protection', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bifacial_gain', models.IntegerField(blank=True, null=True)),
                ('product_warranty', models.IntegerField()),
                ('performance_warranty', models.IntegerField()),
                ('first_year_power_drop', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annual_degradation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('output_at_year_25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manufacturing_capacity', models.CharField(max_length=50)),
                ('bloomberg_tier1', models.BooleanField(default=False)),
                ('pvel_top_performer', models.BooleanField(default=False)),
                ('bis_certified', models.BooleanField(default=True)),
                ('independent_audit', models.BooleanField(default=False)),
                ('certifications', models.JSONField(default=list)),
                ('price_range', models.CharField(max_length=100)),
                ('subsidy_eligible', models.BooleanField(default=True)),
                ('kerala_climate_score', models.IntegerField()),
                ('efficiency_rating', models.IntegerField()),
                ('heat_performance_rating', models.IntegerField()),
                ('warranty_rating', models.IntegerField()),
                ('kerala_climate_rating', models.IntegerField()),
                ('overall_rating', models.CharField(choices=[('excellent', 'Excellent'), ('very-good', 'Very Good'), ('good', 'Good')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solar_panels',
                'ordering': ['-kerala_climate_score'],
            },
        ),
    ]
