# Generated by Django 6.0.1 on 2026-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0049_insert_7kw_solar_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarInverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('inverter_type', models.CharField(choices=[('string', 'String Inverter'), ('hybrid', 'Hybrid Inverter'), ('microinverter', 'Microinverter'), ('optimized-string', 'Optimized String')], max_length=30)),
                ('rating_tier', models.CharField(choices=[('premium', 'Premium'), ('mid-range', 'Mid-Range'), ('value', 'Value')], default='mid-range', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('rated_output_power', models.IntegerField()),
                ('maximum_dc_input', models.IntegerField()),
                ('mppt_trackers', models.IntegerField(default=2)),
                ('maximum_dc_voltage', models.IntegerField()),
                ('maximum_input_current', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('display', models.CharField(default='LED + Mobile App', max_length=100)),
                ('suitable_system_size', models.CharField(blank=True, max_length=100)),
                ('maximum_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('european_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mppt_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dc_oversizing', models.IntegerField()),
                ('ac_overloading', models.IntegerField()),
                ('pid_protection', models.BooleanField(default=True)),
                ('iv_curve_scanning', models.CharField(default='Basic', max_length=100)),
                ('ip_rating', models.CharField(default='IP65', max_length=10)),
                ('corrosion_protection', models.CharField(default='Standard coating', max_length=100)),
                ('operating_temperature', models.CharField(default='-25°C to 60°C', max_length=50)),
                ('cooling', models.CharField(default='Natural convection', max_length=100)),
                ('noise_level', models.CharField(default='<30 dB', max_length=50)),
                ('dc_surge_protection', models.CharField(default='Built-in', max_length=50)),
                ('ac_surge_protection', models.CharField(default='Built-in', max_length=50)),
                ('arc_fault_detection', models.CharField(default='Built-in', max_length=50)),
                ('grid_protection', models.BooleanField(default=True)),
                ('monitoring_app', models.CharField(default='Mobile App', max_length=100)),
                ('real_time_monitoring', models.BooleanField(default=True)),
                ('remote_diagnostics', models.CharField(default='Basic alerts', max_length=100)),
                ('firmware_updates', models.CharField(default='OTA Updates', max_length=100)),
                ('connectivity', models.CharField(default='WiFi / Ethernet', max_length=100)),
                ('warranty_years', models.IntegerField()),
                ('extendable_warranty_years', models.IntegerField(blank=True, null=True)),
                ('certifications', models.JSONField(default=list)),
                ('brand_trust', models.CharField(default='Available', max_length=50)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('countries_served', models.CharField(blank=True, max_length=50)),
                ('global_installations', models.CharField(blank=True, max_length=50)),
                ('price_range', models.CharField(max_length=100)),
                ('kerala_climate_score', models.IntegerField()),
                ('efficiency_rating', models.IntegerField()),
                ('reliability_rating', models.IntegerField()),
                ('warranty_rating', models.IntegerField()),
                ('kerala_climate_rating', models.IntegerField()),
                ('overall_rating', models.CharField(choices=[('excellent', 'Excellent'), ('very-good', 'Very Good'), ('good', 'Good')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'solar_inverters',
                'ordering': ['-kerala_climate_score'],
            },
        ),
    ]
