# Generated by Django 5.2.1 on 2026-07-18 12:44
import goldenray.models.job_application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0051_warrantyservicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('UI/UX Designer', 'UI/UX Designer')], default='UI/UX Designer', max_length=64)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('linkedin', models.URLField(max_length=300)),
                ('portfolio_website', models.URLField(blank=True, default='', max_length=300)),
                ('current_company', models.CharField(blank=True, default='', max_length=255)),
                ('current_role', models.CharField(blank=True, default='', max_length=255)),
                ('total_experience', models.CharField(blank=True, choices=[('0–1 years', '0–1 years'), ('1–3 years', '1–3 years'), ('3–5 years', '3–5 years'), ('5+ years', '5+ years')], default='', max_length=32)),
                ('relevant_experience', models.CharField(blank=True, choices=[('0–1 years', '0–1 years'), ('1–3 years', '1–3 years'), ('3–5 years', '3–5 years'), ('5+ years', '5+ years')], default='', max_length=32)),
                ('current_salary', models.CharField(blank=True, choices=[('Below ₹3 LPA', 'Below ₹3 LPA'), ('₹3–5 LPA', '₹3–5 LPA'), ('₹5–8 LPA', '₹5–8 LPA'), ('₹8–12 LPA', '₹8–12 LPA'), ('₹12+ LPA', '₹12+ LPA')], default='', max_length=32)),
                ('expected_salary', models.CharField(blank=True, choices=[('Below ₹3 LPA', 'Below ₹3 LPA'), ('₹3–5 LPA', '₹3–5 LPA'), ('₹5–8 LPA', '₹5–8 LPA'), ('₹8–12 LPA', '₹8–12 LPA'), ('₹12+ LPA', '₹12+ LPA')], default='', max_length=32)),
                ('notice_period', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('15 days', '15 days'), ('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months')], default='', max_length=32)),
                ('heard_about_us', models.CharField(blank=True, choices=[('LinkedIn', 'LinkedIn'), ('Job Portal', 'Job Portal'), ('Referral', 'Referral'), ('Company Website', 'Company Website'), ('Social Media', 'Social Media'), ('Other', 'Other')], default='', max_length=32)),
                ('resume', models.FileField(upload_to=goldenray.models.job_application.resume_upload_path)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to=goldenray.models.job_application.portfolio_upload_path)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
