# Generated by Django 5.2.1 on 2026-08-19 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0052_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('abbr', models.CharField(help_text='Logo initials, e.g. "SBI".', max_length=12)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('logo_bg', models.CharField(default='#074A4D', help_text='Hex colour behind the logo initials.', max_length=9)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Headline annual rate (%) used for sorting and display.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_loan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upfront_requirement', models.CharField(blank=True, help_text='Down payment / margin, e.g. "10% of project cost".', max_length=160)),
                ('eligibility', models.CharField(blank=True, help_text='Free text, e.g. "CIBIL 700+, salaried or self-employed".', max_length=255)),
                ('cibil_required', models.PositiveIntegerField(default=0, help_text='0 means no published minimum.')),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='0 for zero-fee lenders. Use the note for flat fees.', max_digits=5)),
                ('processing_fee_note', models.CharField(blank=True, help_text='Overrides the %% when set, e.g. "₹500 flat".', max_length=120)),
                ('approval_min_days', models.PositiveIntegerField(default=0)),
                ('approval_max_days', models.PositiveIntegerField(default=0)),
                ('max_tenure_years', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of bullet strings shown on the card.')),
                ('best_for', models.CharField(blank=True, max_length=255)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMI bank',
                'verbose_name_plural': 'EMI banks',
                'db_table': 'emi_bank',
                'ordering': ['sort_order', 'interest_rate'],
            },
        ),
        migrations.CreateModel(
            name='EmiCalculatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_percentage', models.DecimalField(decimal_places=2, default=90, help_text='% of the post-subsidy cost that is financed. The rest is upfront.', max_digits=5)),
                ('subsidy_before_loan', models.BooleanField(default=True, help_text='On: subsidy is deducted first, then the loan %% is applied to the remainder. Off: the loan %% applies to the gross system cost.')),
                ('tenure_min_years', models.PositiveIntegerField(default=1)),
                ('tenure_max_years', models.PositiveIntegerField(default=10)),
                ('tenure_default_years', models.PositiveIntegerField(default=5)),
                ('daily_saving_divisor', models.PositiveIntegerField(default=30, help_text='Daily amount = monthly EMI ÷ this. 30 by policy.')),
                ('loan_amount_min', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('loan_amount_max', models.DecimalField(decimal_places=2, default=600000, max_digits=12)),
                ('loan_step', models.DecimalField(decimal_places=2, default=5000, help_text='Increment for the loan amount +/- buttons and slider.', max_digits=12)),
                ('rate_max', models.DecimalField(decimal_places=2, default=18, help_text='Upper end of the customer-facing rate slider.', max_digits=5)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=9.5, help_text='Fallback when no interest rate rule matches.', max_digits=5)),
                ('panel_life_years', models.PositiveIntegerField(default=25, help_text='Used for the lifetime-savings projection.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMI calculator settings',
                'verbose_name_plural': 'EMI calculator settings',
                'db_table': 'emi_calculator_settings',
            },
        ),
        migrations.CreateModel(
            name='EmiInterestRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('min_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive. Blank = applies to any capacity.', max_digits=6, null=True)),
                ('max_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive. Blank = applies to any capacity.', max_digits=6, null=True)),
                ('min_loan', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive ₹ lower bound. Blank = applies to any loan.', max_digits=12, null=True)),
                ('max_loan', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive ₹ upper bound. Blank = applies to any loan.', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Starting annual rate (%) offered for this band.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_rate', models.DecimalField(decimal_places=2, help_text='Floor (%). A customer-adjusted rate is clamped up to this.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_locked', models.BooleanField(default=False, help_text='Locked rates ignore any customer adjustment entirely.')),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when two rules match. Catch-alls should be low.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMI interest rate rule',
                'verbose_name_plural': 'EMI interest rate rules',
                'db_table': 'emi_interest_rate_rule',
                'ordering': ['-priority', 'min_kw', 'min_loan'],
            },
        ),
        migrations.CreateModel(
            name='EmiSubsidyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "PM Surya Ghar — 3kW and above".', max_length=120)),
                ('min_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive lower bound. Blank = no lower bound.', max_digits=6, null=True)),
                ('max_kw', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive upper bound. Blank = no upper bound.', max_digits=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='₹ deducted from system cost before the loan is sized.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when two bands match the same capacity.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMI subsidy rule',
                'verbose_name_plural': 'EMI subsidy rules',
                'db_table': 'emi_subsidy_rule',
                'ordering': ['-priority', 'min_kw'],
            },
        ),
        migrations.CreateModel(
            name='EmiSystemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown on the tile, e.g. "3kW".', max_length=32)),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=6, unique=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_per_kw', models.DecimalField(decimal_places=2, help_text='₹ per kW. System cost = this × capacity.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_bill_reference', models.DecimalField(decimal_places=2, default=0, help_text='Typical monthly electricity bill for this size. Drives the savings comparison, not the EMI.', max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EMI system size',
                'verbose_name_plural': 'EMI system sizes',
                'db_table': 'emi_system_size',
                'ordering': ['sort_order', 'capacity_kw'],
            },
        ),
    ]
