# Generated by Django 5.2.1 on 2026-09-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0058_emi_3kw_fixed_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='department_name',
            field=models.CharField(blank=True, default='', help_text='snapshot at submission', max_length=120),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='careers.JobPosition id on the CMS service (no FK: different database)', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position_title',
            field=models.CharField(blank=True, default='', help_text='snapshot at submission', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=12),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(default='General application', max_length=200),
        ),
        migrations.CreateModel(
            name='JobApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('received', 'Application received'), ('status', 'Status changed'), ('assigned', 'Assigned to a position'), ('archived', 'Archived'), ('restored', 'Restored'), ('note', 'Note added')], max_length=12)),
                ('from_status', models.CharField(blank=True, default='', max_length=12)),
                ('to_status', models.CharField(blank=True, default='', max_length=12)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.CharField(blank=True, default='', help_text='Studio username, or blank for the system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='goldenray.jobapplication')),
            ],
            options={
                'db_table': 'job_application_event',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='goldenray.jobapplication')),
            ],
            options={
                'db_table': 'job_application_note',
                'ordering': ['-created_at'],
            },
        ),
    ]
