# Generated by Django 5.2.1 on 2026-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenray', '0064_lead_sources_and_general_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcollectionhome',
            name='source',
            field=models.CharField(choices=[('footer', 'Footer — Ready to go solar'), ('home_booking', 'Book a consultation form'), ('contact_page', 'Contact Us page'), ('group_purchase', 'Group Purchase reservation'), ('quotation', 'Quotation request (calculator)'), ('quote_request', 'Quote request (advanced calculator)'), ('referral_partner', 'Referral partner application'), ('warranty_service', 'Warranty service request'), ('career_application', 'Career application'), ('other', 'Website form')], db_index=True, default='other', max_length=32),
        ),
    ]
