from .battery import Battery
from .device_type import DeviceType
from .evcar import EVCar
from .evscooter import EVScooter
from .kseb_tariff import KSEBTariff
from .pincode import Pincode
from .room_size import RoomSize
from .sent_quote import SentQuote
from .solar_installation import SolarInstallation
from .solar_installation_new import SolarInstallationNew
from .solar_panel import SolarPanel
from .wattage import Wattage
from .customer_installation import CustomerInstallation
from .affiliate_application import AffiliateApplication