from .battery import Battery
from .device_type import DeviceType
from .evcar import EVCar
from .evscooter import EVScooter
from .kseb_tariff import KSEBTariff
from .pincode import Pincode
from .sent_quote import SentQuote
from .solar_installation import SolarInstallation
from .solar_installation_new import SolarInstallationNew
from .wattage import Wattage