# Generated by Django 5.0.2 on 2026-04-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('ongrid', 'On-Grid'), ('hybrid', 'Hybrid'), ('upgrade', 'Upgrade')], max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sizes', models.JSONField(default=dict)),
                ('three_phase_sizes', models.JSONField(default=list)),
                ('available_tiers', models.JSONField(default=list)),
                ('battery_configs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('gst_default', models.IntegerField(choices=[(5, '5%'), (12, '12%'), (18, '18%')])),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GlobalCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_rate_year', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_years', models.PositiveSmallIntegerField()),
                ('transport_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('default_dist_km', models.PositiveSmallIntegerField()),
                ('miscellaneous', models.DecimalField(decimal_places=2, max_digits=12)),
                ('office', models.DecimalField(decimal_places=2, max_digits=12)),
                ('elevated_structure_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sheet_structure_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gp_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gi_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('structure_labor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('structure_repair_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Costs',
                'verbose_name_plural': 'Global Costs',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applies_to', models.CharField(choices=[('all', 'All'), ('ongrid', 'On-Grid'), ('hybrid', 'Hybrid'), ('upgrade', 'Upgrade')], max_length=10)),
                ('applies_to_tier', models.CharField(choices=[('all', 'All'), ('base', 'Base'), ('value', 'Value'), ('premium', 'Premium')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TubeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_size', models.CharField(max_length=20, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_override', models.IntegerField(blank=True, choices=[(5, '5%'), (12, '12%'), (18, '18%')], null=True)),
                ('watt', models.IntegerField(blank=True, null=True)),
                ('per_watt', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dcr', models.BooleanField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, choices=[('1P', '1P'), ('3P', '3P'), ('1P-HYB', '1P-HYB'), ('3P-HYB', '3P-HYB')], max_length=10, null=True)),
                ('kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('inverter_type', models.CharField(blank=True, choices=[('ongrid', 'On-Grid'), ('hybrid', 'Hybrid')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='bom.category')),
            ],
        ),
        migrations.CreateModel(
            name='BomFixedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst', models.IntegerField(choices=[(5, '5%'), (12, '12%'), (18, '18%')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.JSONField(default=dict)),
                ('bat_qty', models.JSONField(blank=True, null=True)),
                ('premium_qty', models.JSONField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('is_tube', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_items', to='bom.bomtemplate')),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_bom_entries', to='bom.catalogitem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_bom_items', to='bom.category')),
            ],
        ),
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('ongrid', 'On-Grid'), ('hybrid', 'Hybrid'), ('upgrade', 'Upgrade')], max_length=10)),
                ('tier', models.CharField(blank=True, choices=[('base', 'Base'), ('value', 'Value'), ('premium', 'Premium')], max_length=10)),
                ('bat_config', models.CharField(blank=True, max_length=5)),
                ('from_size', models.CharField(blank=True, max_length=10)),
                ('to_size', models.CharField(blank=True, max_length=10)),
                ('size_rates', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('system_type', 'tier', 'bat_config', 'from_size', 'to_size')},
            },
        ),
        migrations.CreateModel(
            name='StructureTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('tube', 'Tube'), ('fixed', 'Fixed')], max_length=10)),
                ('tube_size', models.CharField(blank=True, max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=10)),
                ('qty', models.JSONField(default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.structuretemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BomSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('variable', models.BooleanField(default=False)),
                ('gst', models.IntegerField(choices=[(5, '5%'), (12, '12%'), (18, '18%')])),
                ('qty', models.JSONField(default=dict)),
                ('premium_qty', models.JSONField(blank=True, null=True)),
                ('bat_qty', models.JSONField(blank=True, null=True)),
                ('premium_bat_qty', models.JSONField(blank=True, null=True)),
                ('filter_type', models.CharField(blank=True, max_length=20)),
                ('filter_phase', models.CharField(blank=True, max_length=20)),
                ('qty_mode', models.CharField(blank=True, max_length=20)),
                ('fixed_qty', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bom.bomtemplate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_slots', to='bom.category')),
            ],
            options={
                'ordering': ['pos'],
                'unique_together': {('template', 'pos')},
            },
        ),
        migrations.CreateModel(
            name='ItemTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('base', 'Base'), ('value', 'Value'), ('premium', 'Premium')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tiers', to='bom.catalogitem')),
            ],
            options={
                'unique_together': {('item', 'tier')},
            },
        ),
    ]
