# Generated by Django 5.2.1 on 2026-09-23 18:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_rate_up_to_3kw', models.DecimalField(decimal_places=2, default=Decimal('5.75'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='EMI rate up to 3 kW (% p.a.)')),
                ('emi_rate_above_3kw', models.DecimalField(decimal_places=2, default=Decimal('7.90'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('30'))], verbose_name='EMI rate above 3 kW (% p.a.)')),
                ('offer_enabled', models.BooleanField(default=True, verbose_name='Show offer')),
                ('offer_title', models.CharField(blank=True, default='Priority 10-Day Installation', max_length=150)),
                ('offer_description', models.CharField(blank=True, default='Fast-tracked scheduling and execution', max_length=300)),
                ('offer_details', models.CharField(blank=True, default='', max_length=300)),
                ('offer_title_ml', models.CharField(blank=True, default='10 ദിവസത്തിനുള്ളിൽ മുൻഗണനാ ഇൻസ്റ്റലേഷൻ', max_length=150, verbose_name='Offer title (Malayalam)')),
                ('offer_description_ml', models.CharField(blank=True, default='വേഗത്തിലുള്ള ഷെഡ്യൂളിംഗും ഇൻസ്റ്റലേഷനും', max_length=300, verbose_name='Offer description (Malayalam)')),
                ('offer_details_ml', models.CharField(blank=True, default='', max_length=300, verbose_name='Offer details (Malayalam)')),
                ('offer_valid_from', models.DateField(blank=True, null=True)),
                ('offer_valid_until', models.DateField(blank=True, null=True)),
                ('offer_image', models.FileField(blank=True, upload_to='quotation/offers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('offer_image_url', models.URLField(blank=True, default='https://golden-ray.b-cdn.net/icons/37.png')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quotation Settings',
                'verbose_name_plural': 'Quotation Settings',
            },
        ),
    ]
