# Generated by Django 5.2.1 on 2026-09-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_emi_rate_by_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsettings',
            name='emi_rate_above_threshold',
        ),
        migrations.RemoveField(
            model_name='quotationsettings',
            name='emi_rate_at_or_below_threshold',
        ),
        migrations.RemoveField(
            model_name='quotationsettings',
            name='emi_rate_threshold',
        ),
    ]
