# Generated by Django 5.2.1 on 2026-09-27 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_emi_rates_move_to_emi_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Jose V P".', max_length=80)),
                ('location', models.CharField(help_text='e.g. "Vadakkal, Alappuzha".', max_length=80)),
                ('system_label', models.CharField(default='5 kW System', max_length=40)),
                ('installed_on', models.DateField(help_text='Only the month and year are printed.')),
                ('quote', models.TextField(max_length=600)),
                ('quote_ml', models.TextField(blank=True, help_text='Printed on Malayalam quotations; the English quote is used when blank.', max_length=600, verbose_name='Quote (Malayalam)')),
                ('photo', models.FileField(blank=True, upload_to='quotation/testimonials/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('photo_url', models.URLField(blank=True)),
                ('bill_before', models.PositiveIntegerField(default=3200, verbose_name='Monthly bill before solar (₹)')),
                ('bill_after', models.PositiveIntegerField(default=200, verbose_name='Monthly bill after solar (₹)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower comes first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quotation testimonial',
                'verbose_name_plural': 'Quotation testimonials',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
