# Generated by Django 5.2.1 on 2026-07-22 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='cdn_url',
            field=models.URLField(blank=True, help_text='BunnyCDN URL (auto-filled on upload)', max_length=1000),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='CDN folder: cms/<collection>/ (cms/general/ if unset)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='storage_path',
            field=models.CharField(blank=True, help_text='path inside the Bunny storage zone', max_length=500),
        ),
    ]
