from rest_framework import serializers
from ..models import SolarInverter


class SolarInverterSerializer(serializers.ModelSerializer):
    class Meta:
        model = SolarInverter
        fields = [
            "id",
            "brand",
            "name",
            "inverter_type",
            "rating_tier",
            "image_url",
            "description",
            "rated_output_power",
            "maximum_dc_input",
            "mppt_trackers",
            "maximum_dc_voltage",
            "maximum_input_current",
            "weight",
            "display",
            "suitable_system_size",
            "maximum_efficiency",
            "european_efficiency",
            "mppt_efficiency",
            "dc_oversizing",
            "ac_overloading",
            "pid_protection",
            "iv_curve_scanning",
            "ip_rating",
            "corrosion_protection",
            "operating_temperature",
            "cooling",
            "noise_level",
            "dc_surge_protection",
            "ac_surge_protection",
            "arc_fault_detection",
            "grid_protection",
            "monitoring_app",
            "real_time_monitoring",
            "remote_diagnostics",
            "firmware_updates",
            "connectivity",
            "warranty_years",
            "extendable_warranty_years",
            "certifications",
            "brand_trust",
            "year_founded",
            "countries_served",
            "global_installations",
            "price_range",
            "kerala_climate_score",
            "efficiency_rating",
            "reliability_rating",
            "warranty_rating",
            "kerala_climate_rating",
            "overall_rating",
            "created_at",
            "updated_at",
        ]
        read_only_fields = ["id", "created_at", "updated_at"]
