# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(help_text="stable key, e.g. 'content-manager'", max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='{"faqs": ["view", "create", "edit"], ...}')),
                ('legacy_role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'Author')], default='author', help_text="value sent in the JWT 'role' claim for the goldenray backend", max_length=16)),
                ('is_system', models.BooleanField(default=False, help_text='seeded archetype; editable but not deletable')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_role',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='access_role',
            field=models.ForeignKey(blank=True, help_text='Phase 1 permission matrix; overrides the legacy role when set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
    ]
