# Generated by Django 5.2.1 on 2026-07-20 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=list, help_text='Strapi-blocks array')),
                ('introduction', models.JSONField(blank=True, default=list, help_text='Strapi-blocks array')),
                ('read_time', models.PositiveIntegerField(blank=True, help_text='minutes', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('published_on', models.DateTimeField(blank=True, help_text='author-set display date', null=True)),
                ('warning', models.TextField(blank=True, help_text="→ 'important' callout", null=True)),
                ('insights', models.TextField(blank=True, help_text="→ 'key insight' callout", null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
                ('badges', models.ManyToManyField(blank=True, related_name='entries', to='catalog.badge')),
                ('categories', models.ManyToManyField(blank=True, related_name='entries', to='catalog.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.collection')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='catalog.tag')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_entry',
                'ordering': ['sort_order', '-published_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='shared.rich-text', max_length=120)),
                ('body', models.JSONField(blank=True, default=list, help_text='Strapi-blocks array')),
                ('order', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='content.entry')),
            ],
            options={
                'db_table': 'content_content_block',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(help_text='matches a TemplateAttributeSlot.key', max_length=60)),
                ('value', models.JSONField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='content.entry')),
            ],
            options={
                'db_table': 'content_entry_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(help_text='matches a TemplateImageGroup.key', max_length=60)),
                ('position', models.IntegerField(default=0, help_text='order within a repeatable group')),
                ('external_url', models.URLField(blank=True, help_text='external/CDN URL alternative', max_length=1000)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.entry')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'db_table': 'content_entry_image',
                'ordering': ['group_key', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='content.entry')),
            ],
            options={
                'db_table': 'content_seo',
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['collection', 'status', 'published_on'], name='content_ent_collect_8f48ea_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['is_featured'], name='content_ent_is_feat_81615d_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['sort_order'], name='content_ent_sort_or_34ce2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='uniq_entry_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='entryattributevalue',
            constraint=models.UniqueConstraint(fields=('entry', 'slot_key'), name='uniq_entry_attr_slot'),
        ),
    ]
