# Generated by Django 5.2.1 on 2026-08-19 17:50

import content.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="set when status becomes 'deleted'", null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=255, validators=[content.validators.validate_entry_slug]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='EntrySlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='inactive aliases are kept for audit but never resolved')),
                ('note', models.CharField(blank=True, help_text='why this alias exists', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_slug_aliases', to='catalog.collection')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='content.entry')),
            ],
            options={
                'verbose_name_plural': 'entry slug history',
                'db_table': 'content_entry_slug_history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['collection', 'slug', 'is_active'], name='content_ent_collect_1bb682_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('collection', 'slug'), name='uniq_active_slug_alias_per_collection')],
            },
        ),
    ]
