# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediaasset_cdn_url_mediaasset_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=40)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('address_locality', models.CharField(blank=True, help_text='city', max_length=120)),
                ('address_region', models.CharField(blank=True, help_text='state', max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('lead_notification_emails', models.CharField(blank=True, help_text='comma-separated; who is emailed when a lead arrives', max_length=500)),
                ('application_notification_emails', models.CharField(blank=True, help_text='comma-separated; who is emailed when a career application arrives', max_length=500)),
                ('notify_on_new_lead', models.BooleanField(default=True)),
                ('notify_on_new_application', models.BooleanField(default=True)),
                ('default_meta_description', models.TextField(blank=True, help_text='used when a page has no description of its own')),
                ('careers_accepting_general_applications', models.BooleanField(default=True, help_text='show the general application form on the careers page')),
                ('careers_intro', models.TextField(blank=True, help_text='short line above Open Positions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'db_table': 'siteconfig_settings',
            },
        ),
    ]
