# Generated by Django 5.2.1 on 2026-09-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediaasset_cdn_url_mediaasset_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='short description shown on the careers page')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'careers_department',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text="falls back to the record's own title; ~60 chars", max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='70–160 characters reads best in results')),
                ('canonical_url', models.URLField(blank=True, help_text='only when this URL duplicates another', max_length=1000)),
                ('schema_type', models.CharField(choices=[('none', 'No structured data'), ('WebPage', 'Web page'), ('Article', 'Article'), ('FAQPage', 'FAQ page'), ('JobPosting', 'Job posting'), ('Organization', 'Organization'), ('BreadcrumbList', 'Breadcrumb list')], default='none', max_length=32)),
                ('schema_extra', models.JSONField(blank=True, default=dict, help_text='only the structured fields the generator cannot infer from the record')),
                ('noindex', models.BooleanField(default=False, help_text='ask search engines not to index this URL')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='public URL: /career/<slug>', max_length=220, unique=True)),
                ('location', models.CharField(max_length=160)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=16)),
                ('experience_required', models.CharField(blank=True, help_text="e.g. '2–4 years'", max_length=120)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True, help_text='one per line')),
                ('requirements', models.TextField(blank=True, help_text='one per line')),
                ('benefits', models.TextField(blank=True, help_text='one per line; omit if the design has no benefits block')),
                ('application_instructions', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('sort_order', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='careers.department')),
                ('og_image', models.ForeignKey(blank=True, help_text='social share image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careers_job_position',
                'ordering': ['sort_order', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='careers_job_status_132a66_idx'), models.Index(fields=['department', 'status'], name='careers_job_departm_22d76d_idx')],
            },
        ),
    ]
